prometheus:
  prometheusSpec:
    replicas: 2
    retention: 15d
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
grafana:
  enabled: false
